language: csharp
dist: trusty
sudo: false
dotnet: 2.0.3

matrix:
  fast_finish: true
  
  include:
    - os: linux
    - os: osx
      osx_image: xcode9.2

  allow_failures:
    - os: osx
    

env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - TMPDIR=/tmp

script:
  - travis_wait ./build.sh

notifications:
  email: false
